# NNETHERR
# Theme create by: @nnetherr
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "nord"

# ========= Border =========
file_panel_border = "#808080"
sidebar_border = "#808080"
footer_border = "#808080"

# ========= Border Active =========
file_panel_border_active = "#ffffff"
sidebar_border_active = "#ffffff"
footer_border_active = "#ffffff"
modal_border_active = "#ffffff"

# ========= Background (bg) =========
full_screen_bg = "#000000"
file_panel_bg = "#000000"
sidebar_bg = "#000000"
footer_bg = "#000000"
modal_bg = "#000000"

# ========= Foreground (fg) =========
full_screen_fg = "#e5e9f0"
file_panel_fg = "#e5e9f0"
sidebar_fg = "#e5e9f0"
footer_fg = "#e5e9f0"
modal_fg = "#e5e9f0"

# ========= Special Color =========
cursor = "#A5a5a5"
correct = "#a5a5a5"
error = "#bf616a"
hint = "#8fbcbb"
cancel = "#d8dee9"
# Gradient color can only have two color!
gradient_color = ["#81a1c1", "#bf616a"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#A5a5a5"
file_panel_top_path = "#A5a5a5"
file_panel_item_selected_fg = "#c7c7c7"
file_panel_item_selected_bg = "#7c7c7c"

# ========= Sidebar Special Items =========
sidebar_title = "#A5a5a5"
sidebar_item_selected_fg = "#A5a5a5"
sidebar_item_selected_bg = "#2e3440"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#e5e9f0"
modal_cancel_bg = "#4c566a"

modal_confirm_fg = "#e5e9f0"
modal_confirm_bg = "#bf616a"

# ========= Help Menu =========
help_menu_hotkey = "#8fbcbb"
help_menu_title = "#81a1c1"